apiVersion: v1
kind: Service
metadata:
  name: nessus-clusterip-service  # Nom unique pour le service ClusterIP
spec:
  type: ClusterIP
  ports:
    - port: 8834  # Port de Nessus
      targetPort: 8834
  selector:
    app: nessus  # Sélectionne les pods avec le label app: nessus
