apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessus-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nessus
  template:
    metadata:
      labels:
        app: nessus
    spec:
      containers:
      - name: nessus
        image: tenable/nessus:latest
        ports:
        - containerPort: 8834
