apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-np-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30004
  type: NodePort 
