apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200          # The default Kibana port
      targetPort: 9200     # The target port inside the container
      nodePort: 30004      # The node port to access Kibana outside the cluster
  type: NodePort 
