apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601          # The default Kibana port
      targetPort: 5601     # The target port inside the container
      nodePort: 30003      # The node port to access Kibana outside the cluster
  type: NodePort           # Expose the service using a NodePort
