# Logstash Dockerfile
FROM docker.elastic.co/logstash/logstash:7.10.0

# Optional: Add custom configuration if needed
# Copy custom configuration to logstash folder
# COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf

EXPOSE 5044 9600

CMD ["logstash"]
