apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      http {
        port => 5044  # Port where Logstash listens for incoming data
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]  # Replace with your Elasticsearch service if necessary
        index => "nessus-%{+YYYY.MM.dd}"  # Index pattern for Nessus logs
      }
    }
