apiVersion: v1
kind: Service
metadata:
  name: logstash-service  # Name of the Logstash service
spec:
  type: ClusterIP
  ports:
    - port: 5044  # Logstash port
      targetPort: 5044
  selector:
    app: logstash
