apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 8080          # The port that Ollama is listening to in the container
      targetPort: 8080     # The target port inside the container
      nodePort: 30002      # The node port to access Ollama outside the cluster
  type: NodePort           # Expose the service using a NodePort
